### ISSUE TITLE
command 'gtestExplorer.xxx' not found

### ISSUE THREAD

**Issue by shelper** [DavidSchuldenfrei/gtest-adapter#16]
your plugin was working well on my vscode on ubuntu, and suddenlty it cannot show any test in the tree view, and run any command with GTest:xxx i got error saying  `command 'gtestExplorer.xxx' not found`, I tried reinstall everything including vscode, and none worked...

i tried on different pc and everything works as expected..... please help !

**Comment by shelper** [comment]
i think i found the issue, and i dont know why that happened, so in the folder out/ there is a file lineinfo.js, should be Lineinfo.js on ubuntu . the captical of the first letter of the file is critical

**Comment by DavidSchuldenfrei** [comment]
It should be **L**ine**I**nfo.js (capital L and i).
I checked that the latest  version creates this file with the proper capitalization. If you further encounter this issue, please reopen this issue

**Comment by shelper** [comment]
it still outputs 'lineInfo.js` with 1.3.0

**Comment by thehans** [comment]
Hello, I'm also seeing this issue `command gTestExplorer.run not found` on Linux Mint 19.
vscode 1.33.0
GoogleTest Adapter 1.8.3  

Not sure if I have configured something wrong as I'm still learning to set up gtest for the first time, but I also don't even see any `lineinfo.js` file anywhere regardless of case.   I checked with `find ./ -iname lineinfo.js` from my project's top level directory.
