### ISSUE TITLE
Running an individual test is unintuitive

### ISSUE THREAD

**Issue by ftrofin** [DavidSchuldenfrei/gtest-adapter#17]
First of all, thanks for providing this extension, I love it and it's very useful for us. I noticed a small UI issue which makes it for an unintuitive (poor) user experience: Suppose you have a selection in the list of tests:
![image](https://user-images.githubusercontent.com/8718388/46880556-dba14780-cdfd-11e8-8575-57e0ca7b194f.png)
I left clicked on "TestCreateRegistryKey" and the entry is selected. Now I *right* click on another test in that list and choose Run:
![image](https://user-images.githubusercontent.com/8718388/46880696-3aff5780-cdfe-11e8-899c-5d73716197a7.png)
Notice how "TestCreateSubkey" also shows selected in addition to "TestCreateRegistryKey". When I release the mouse button (after clicking on Run), TestCreateSubkey is deselected and TestCreateRegistryKey remains selected and VS Code runs TestCreateRegistryKey instead!

So two issues here:
- the selection highlighting is unintuitive.
- The wrong test is executed (whatever test happend to be selected instead of the one I right clicked).

If multi-selection would have been allowed, this would have made more sense. But since only one selection can be made I suggest that right-clicking an entry in the list also changes the selection before popping up that context menu, so when Run is chosen, the correct test is executed.

Environment:
MacOS 10.13.6
VS Code Version 1.28.1 (1.28.1)
GoogleTest Adapter version 1.2.4
Latest gtest version (1.8.1)

**Comment by DavidSchuldenfrei** [comment]
@ftrofin I am glad that you like this extension, and I appreciate your feedback.
I agree that this is counter-ituitive, and I have myself mistakenly run the wrong test. I believe that this is a limitation of VsCode API. I asked on StackOverflow, if there is a way to get this to work.

**Comment by DavidSchuldenfrei** [comment]
Solved in release 1.2.6
@ftrofin If you have any further suggestions to make this extension more useful, please feel free to add further issues. All feedbacks (and 5 star ratings) are welcome.

**Comment by DavidSchuldenfrei** [comment]
Solved in release 1.3.0
@ftrofin If you have any further suggestions to make this extension more useful, please feel free to add further issues. All feedbacks (and 5 star ratings) are welcome.

**Comment by ftrofin** [comment]
Works perfectly now! Thanks a lot, this is so much better!
