### ISSUE TITLE
"Finished running all tests" shows up as a test entry in the panel

### ISSUE THREAD

**Issue by ftrofin** [DavidSchuldenfrei/gtest-adapter#20]
This is pretty self-explanatory:
![image](https://user-images.githubusercontent.com/8718388/46896045-10c68d80-ce30-11e8-886d-7a86f63bc3d6.png)
You can actually selected and choose "Run" and the test adapter will attempt to run it:
![image](https://user-images.githubusercontent.com/8718388/46896065-2dfb5c00-ce30-11e8-9d70-67bb7dfec179.png)

Expected: should not show up in the list of tests.

Environment:
MacOS 10.13.6
VS Code Version 1.28.1 (1.28.1)
GoogleTest Adapter version 1.2.4
Latest gtest version (1.8.1)

**Comment by DavidSchuldenfrei** [comment]
@ftrofin Thanks for reporting this. I guess that the output of GoogleTest is platform dependent.
This should now be fixed with release 1.2.5.
I am closing this issue. Please reopen if you encounter further issues

**Comment by ftrofin** [comment]
Thanks David for the speedy fix! Do you know when the 1.2.5 will be released?
