### ISSUE TITLE
it still outputs 'lineInfo.js` with 1.3.0 on linux

### ISSUE THREAD

**Issue by shelper** [DavidSchuldenfrei/gtest-adapter#22]
_Originally posted by @shelper in https://github.com/DavidSchuldenfrei/gtest-adapter/issues/16#issuecomment-429651449_

i checked on my mac and although the file name is ·lineInfo.js· but the plugin still works. it's just on Ubuntu that noncapital 'L` fails the plugin

**Comment by DavidSchuldenfrei** [comment]
This should be fixed with v 1.3.1
If you still have problems , please open a new issue.
