### ISSUE TITLE
Tests should respect cwd specified in launch.json

### ISSUE THREAD

**Issue by wasabinza** [DavidSchuldenfrei/gtest-adapter#24]
The current test runner explicitly uses the workspace as the folder to run the tests.
If the launch.json config specifies a cwd then we should launch in that folder instead.

**Comment by DavidSchuldenfrei** [comment]
I fixed the issue with PR #26  . I hope to publish a new version of the extension by tomorrow with this fix.

**Comment by DavidSchuldenfrei** [comment]
This is now fixed in 1.5.0
