### ISSUE TITLE
build when tests are run

### ISSUE THREAD

**Issue by umarmir** [DavidSchuldenfrei/gtest-adapter#25]
is there some way the adapter can be configured to build the project whenever the run tests button is clicked?

alternatively is it possible to run tests automatically after build?

**Comment by DavidSchuldenfrei** [comment]
I fixed the issue with PR #27 . I hope to publish a new version of the extension by tomorrow with this feature.
There will be a setting (`gtest-adapter.runAfterBuild`) which defaults to `false`, so as not to slow build times, but when set to `true` will run all tests after each build. Please note that this will only happen if `gtest-adapter.refreshAfterBuild` is set to `true` also (it is its default value)

**Comment by DavidSchuldenfrei** [comment]
@umarmir Thanks for the suggestion. THis is now fixed in 1.5.0

**Comment by umarmir** [comment]
Thanks, tested it out. Works great.
