### ISSUE TITLE
Seamlessly support multiple gtest executables

### ISSUE THREAD

**Issue by cdunford** [DavidSchuldenfrei/gtest-adapter#29]
I work on a relatively large codebase. We organize our code such that layers are grouped into a single gtest executable, and our multi-layer application ends up having several gtest executables in a single project/repository. It would be great if there was a way to support multiple launch configurations at a time. I know we can switch launch configurations easily, but it would be good if we could load up multiple configurations at once so we can run the full repository's tests in one shot; this would be great for when we run tests after build as well. One idea would be to have a pattern to match the name of the launch configuration (rather than matching a single name) so we can follow a convention which configurations are for gtests and others which may not be.

**Comment by DavidSchuldenfrei** [comment]
Hi @cdunford,
Thanks for your suggestion. 
I am thinking of the following:
1. Allow debugconfig to also be an array of strings (where all the strings would be one debug configuration)
2. Each config would be a node in the tree, named like the config, and the previous tree would be subnodes of this node
3. When selecting "Switch Configuration" there would be an option to select several debug configs (maybe at a later time) 
4. When selecting "Run All", all configs would run. 
5. When selecting "Debug All", only the active config (the config of the current node) would run. 

I know that 4 and 5 involve a discrepancy but I don't see how to get around it. 

Any thoughts? 

I am a little busy, so I won't be able to get to this until next week at the earliest.

**Comment by DavidSchuldenfrei** [comment]
@cdunford Do note that I use debug configs (from launch.json) to know how to run the tests, so even if you have a convention for naming tests, you would still need to configure your launch settings

**Comment by cdunford** [comment]
Yeah I know

**Comment by DavidSchuldenfrei** [comment]
@cdunford This is now implemented in 1.6.0 (without regex support for now). Let me know how it goes. I will try to add regex support at a later date
