### ISSUE TITLE
Tests don't appear (1.6.1)

### ISSUE THREAD

**Issue by leonardo-faria** [DavidSchuldenfrei/gtest-adapter#32]
Using version 1.6.1 of this extension.
After selecting any tests (after pressing "Switch test configuration" and selecting 1 or more tests), no tests appear in "Google Tests" window. I'm using 1.8.0 of google test.

At the moment switching from 1.6.1 to 1.6.0 solves the issue

**Comment by DavidSchuldenfrei** [comment]
@leonardo-faria Hi,
Thanks for reporting this. I need further information to reproduce/fix this. Does the issue occur when you upgrade to 1.6.1 without changing the configuration?
Could you send me a copy of your configuration (settings.json and launch.json) from the .vscode folder.

**Comment by Junch** [comment]
I have the same issue as leonardo-faria said. It can be reproduced as below.
1. Click the "Switch test configuration"
2. Uncheck the current selection and click OK. The tests will disappear from the "Google Tests" windows.
3. Click the "Switch test configuration" again and check the previous selection. No tests will be added to the "Google Tests" windows.

**Comment by DavidSchuldenfrei** [comment]
@leonardo-faria, @Junch 
Thanks,
I just fixed this. Please try upgrading to 1.6.2, and let me know if this fixes it
David

**Comment by leonardo-faria** [comment]
It's working now, thank you for the quick fix @DavidSchuldenfrei :+1:
