### ISSUE TITLE
Tests don't run after upgrading to 1.8.2 with VSCode 1.32.3

### ISSUE THREAD

**Issue by PomLover** [DavidSchuldenfrei/gtest-adapter#36]

**Comment by alliaces** [comment]
Hello,
I have the same issue. It's running good if I go back to the gtest-adapter 1.8.1.
On 1.8.2, I have this kind of error when I try to pass a single test (on Log (Window)):

> [2019-04-03 09:47:32.133] [renderer1] [error] spawn "pathToMyTest" ENOENT: Error: spawn "pathToMyTest" ENOENT
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
> 	at onErrorNT (internal/child_process.js:406:16)
> 	at process._tickCallback (internal/process/next_tick.js:63:19)

Thanks!

**Comment by DavidSchuldenfrei** [comment]
Sorry, I uploaded an incomplete version. I (believe) I fixed this in 1.8.3
@alliaces , @PomLover  can you please confirm it works for you also

**Comment by alliaces** [comment]
It works perfectly, thanks a lot !

**Comment by PomLover** [comment]
> Sorry, I uploaded an incomplete version. I (believe) I fixed this in 1.8.3
> @alliaces , @PomLover can you please confirm it works for you also

version 1.8.3 works great. Thanks.
